name: Render PlantUML to Wiki

on:
  push:
    branches: [ main, master ]
    paths:
      - '**/*.puml'
  workflow_dispatch:

permissions:
  contents: write  # Wikiへのpushに必要

concurrency:
  group: plantuml-wiki-${{ github.ref }}
  cancel-in-progress: false

jobs:
  render-and-publish:
    name: Render .puml and publish to Wiki
    runs-on: ubuntu-latest

    steps:
      - name: Checkout aiCamera repo
        uses: actions/checkout@v4

      # Wiki（<repo>.wiki）は別リポジトリとして存在します。別パスにチェックアウト
      - name: Checkout Wiki repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki

      - name: Install PlantUML & Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml graphviz

      # 既存のPNG画像を使用（PlantUMLフォルダ内の既存画像を直接利用）
      - name: Copy existing PNG images
        run: |
          echo "Using existing PNG images from PlatUML folder"
          ls -la PlatUML/*.png || echo "No PNG files found in PlatUML folder"

      # Wiki 側の出力ルートをクリアし、既存のPNG画像をコピー
      - name: Sync existing images into wiki/uml
        run: |
          rm -rf wiki/uml
          mkdir -p wiki/uml
          # PlatUMLフォルダの既存PNG画像をwiki/umlへコピー
          if ls PlatUML/*.png 1> /dev/null 2>&1; then
            cp PlatUML/*.png wiki/uml/
            echo "Copied PNG files to wiki/uml:"
            ls -la wiki/uml/
          else
            echo "No PNG files found in PlatUML folder"
          fi

      # UML画像の一覧ページを自動生成（UML-Diagrams.md）。既存Home.mdが無ければ作成。
      - name: Generate Wiki index page
        shell: bash
        run: |
          INDEX_FILE="wiki/UML-Diagrams.md"
          echo "# UML Diagrams (auto-generated)" > "$INDEX_FILE"
          echo "" >> "$INDEX_FILE"
          echo "_Updated from commit \`${GITHUB_SHA}\`_" >> "$INDEX_FILE"
          echo "" >> "$INDEX_FILE"

          # 画像一覧をMarkdownデータとして追記
          while IFS= read -r -d '' IMG; do
            REL="${IMG#wiki/}"
            TITLE=$(basename "$REL")
            echo "## ${TITLE}" >> "$INDEX_FILE"
            echo "" >> "$INDEX_FILE"
            echo "![${TITLE}](${REL})" >> "$INDEX_FILE"
            echo "" >> "$INDEX_FILE"
          done < <(find wiki/uml -type f \( -name '*.png' -o -name '*.svg' \) -print0 | sort -z)

          # Home.md が無ければ作成（リンク追加）
          if [ ! -f wiki/Home.md ]; then
            {
              echo "# aiCamera Wiki"
              echo
              echo "- [UML Diagrams](UML-Diagrams)"
            } > wiki/Home.md
          else
            grep -q "UML Diagrams" wiki/Home.md || echo "- [UML Diagrams](UML-Diagrams)" >> wiki/Home.md
          fi

      - name: Commit & Push to Wiki
        run: |
          cd wiki
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update UML diagrams from ${GITHUB_SHA}" || echo "No changes to commit"
          git push